extends: default
ignore:
  - .cr-release-packages/
  - charts/*/templates/
  - charts/*/values.yaml
rules:
  comments:
    min-spaces-from-content: 1
  document-start: false
  line-length:
    max: 120
  truthy:
    check-keys: false
