{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jsonic.fullname" . }}
  namespace: {{ include "jsonic.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: jsonic
    {{- include "jsonic.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.jsonic.backend }}
  {{- if .databaseUrl }}
  DATABASE_URL: {{ .databaseUrl | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ include "jsonic.secret.databaseUrl" $ | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ include "jsonic.secret.jwtSecret" $ | b64enc | quote }}
  SESSION_SECRET: {{ include "jsonic.secret.sessionSecret" $ | b64enc | quote }}
  DATA_ENCRYPTION_KEY: {{ include "jsonic.secret.dataEncryptionKey" $ | b64enc | quote }}
  {{- with .auth.google }}
  GOOGLE_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}
  {{- with .auth.github }}
  GITHUB_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}
  {{- with .auth.microsoft }}
  MICROSOFT_CLIENT_ID: {{ .clientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}
  {{- with .mailer }}
  MAILER_SMTP_URL: {{ .smtpUrl | b64enc | quote }}
  MAILER_SMTP_USER: {{ .smtpUser | b64enc | quote }}
  MAILER_SMTP_PASSWORD: {{ .smtpPassword | b64enc | quote }}
  {{- end }}
  ENTERPRISE_LICENSE_KEY: {{ .enterpriseLicenseKey | b64enc | quote }}
  {{- with .auth.saml }}
  SAML_CERT: {{ .cert | b64enc | quote }}
  {{- end }}
  {{- with .auth.oidc }}
  OIDC_CLIENT_ID: {{ .clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .clickhouse .clickhouse.allowAuditLogs }}
  {{- if .clickhouse.user }}
  CLICKHOUSE_USER: {{ .clickhouse.user | b64enc | quote }}
  {{- else if or $.Values.clickhouse.enabled $.Values.externalClickhouse.host }}
  CLICKHOUSE_USER: {{ include "jsonic.secret.clickhouseUser" $ | b64enc | quote }}
  {{- end }}
  {{- if .clickhouse.password }}
  CLICKHOUSE_PASSWORD: {{ .clickhouse.password | b64enc | quote }}
  {{- else if or $.Values.clickhouse.enabled $.Values.externalClickhouse.host }}
  CLICKHOUSE_PASSWORD: {{ include "jsonic.secret.clickhousePassword" $ | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .redisUrl }}
  REDIS_URL: {{ .redisUrl | b64enc | quote }}
  {{- else if or $.Values.redis.enabled $.Values.externalRedis.host }}
  REDIS_URL: {{ include "jsonic.secret.redisUrl" $ | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
